const API_BASE = window.THREADLINE_API_URL || '';
const state = { token: localStorage.getItem('threadline_token'), mode: 'login', busy: false };
const $ = (id) => document.getElementById(id);

function setHealth(ready, detail) { $('health-dot').classList.toggle('ready', ready); $('health-label').textContent = ready ? 'Pipeline ready' : 'Pipeline unavailable'; $('health-detail').textContent = detail; }
function setUser(user) { const loggedIn = Boolean(user && state.token); $('user-card').hidden = !loggedIn; $('auth-button').hidden = loggedIn; $('login-hint').textContent = loggedIn ? '' : 'Sign in to unlock the assistant.'; if (loggedIn) { $('user-email').textContent = user.email || 'Signed in'; $('user-avatar').textContent = (user.email || '?')[0].toUpperCase(); } }
async function api(path, options = {}) { const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) }; if (state.token) headers.Authorization = `Bearer ${state.token}`; const response = await fetch(`${API_BASE}${path}`, { ...options, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || 'Something went wrong.'); return data; }

async function checkHealth() { try { const data = await api('/health'); const ready = data.llm_ready && data.retriever_ready && data.rag_chain_ready; setHealth(ready, ready ? 'LLM, retriever, and RAG chain are online.' : 'The service is still warming up.'); } catch { setHealth(false, 'Start the FastAPI service to connect this workspace.'); } }
async function restoreSession() { if (!state.token) return setUser(null); try { setUser(await api('/auth/me')); } catch { localStorage.removeItem('threadline_token'); state.token = null; setUser(null); } }

function addMessage(kind, text, sources = []) { $('empty-state').hidden = true; const element = document.createElement('article'); element.className = `message ${kind}`; element.innerHTML = `<div class="message-meta">${kind === 'user' ? 'You' : 'Assistant'}</div><div class="message-text"></div>`; element.querySelector('.message-text').textContent = text; if (sources.length) { const details = document.createElement('details'); details.className = 'sources'; details.innerHTML = `<summary>${sources.length} source${sources.length === 1 ? '' : 's'} found</summary>`; sources.forEach((source) => { const item = document.createElement('div'); item.className = 'source-item'; item.innerHTML = `<strong>${escapeHtml(source.source || 'Document')}</strong>${source.page ? ` · page ${source.page}` : ''}<br>${escapeHtml(source.snippet || '')}`; details.appendChild(item); }); element.appendChild(details); } $('messages').appendChild(element); return element; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[character])); }

async function ask(query) { if (!state.token) return openAuth(); if (state.busy) return; state.busy = true; $('query-input').disabled = true; $('query-form').querySelector('button').disabled = true; addMessage('user', query); const answer = addMessage('answer', 'Thinking...'); const text = answer.querySelector('.message-text'); try { const data = await api('/query', { method:'POST', body:JSON.stringify({ query, k:4, show_sources:$('source-toggle').checked }) }); text.textContent = data.answer; if (data.sources?.length) { const details = document.createElement('details'); details.className = 'sources'; details.innerHTML = `<summary>${data.sources.length} sources found</summary>`; data.sources.forEach((source) => { const item = document.createElement('div'); item.className = 'source-item'; item.innerHTML = `<strong>${escapeHtml(source.source || 'Document')}</strong>${source.page ? ` · page ${source.page}` : ''}<br>${escapeHtml(source.snippet || '')}`; details.appendChild(item); }); answer.appendChild(details); } } catch (error) { text.textContent = error.message; } finally { state.busy = false; $('query-input').disabled = false; $('query-form').querySelector('button').disabled = false; $('query-input').focus(); } }

async function upload(file) { $('upload-status').textContent = `Indexing ${file.name}...`; const form = new FormData(); form.append('file', file); try { const data = await api('/ingest', { method:'POST', body:form }); $('upload-status').textContent = `${data.filename} · ${data.chunks_stored} chunks stored`; checkHealth(); } catch (error) { $('upload-status').textContent = error.message; } }
function openAuth() { $('auth-modal').hidden = false; $('email-input').focus(); } function closeAuth() { $('auth-modal').hidden = true; $('auth-error').textContent = ''; }

$('query-form').addEventListener('submit', (event) => { event.preventDefault(); const input = $('query-input'); const query = input.value.trim(); if (!query) return; input.value = ''; ask(query); });
$('query-input').addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); $('query-form').requestSubmit(); } }); $('auth-button').addEventListener('click', openAuth); $('modal-close').addEventListener('click', closeAuth); $('auth-modal').addEventListener('click', (event) => { if (event.target === $('auth-modal')) closeAuth(); });
$('logout-button').addEventListener('click', () => { localStorage.removeItem('threadline_token'); state.token = null; setUser(null); }); $('file-input').addEventListener('change', (event) => { if (event.target.files[0]) upload(event.target.files[0]); }); ['dragenter','dragover'].forEach((name) => $('dropzone').addEventListener(name, (event) => { event.preventDefault(); $('dropzone').classList.add('dragging'); })); ['dragleave','drop'].forEach((name) => $('dropzone').addEventListener(name, (event) => { event.preventDefault(); $('dropzone').classList.remove('dragging'); })); $('dropzone').addEventListener('drop', (event) => { if (event.dataTransfer.files[0]) upload(event.dataTransfer.files[0]); });
$('switch-auth').addEventListener('click', () => { state.mode = state.mode === 'login' ? 'signup' : 'login'; $('auth-title').textContent = state.mode === 'login' ? 'Welcome back.' : 'Create your workspace.'; $('auth-submit').innerHTML = state.mode === 'login' ? 'Sign in <span>→</span>' : 'Create account <span>→</span>'; $('switch-auth').innerHTML = state.mode === 'login' ? 'Need an account? <strong>Create one</strong>' : 'Already have an account? <strong>Sign in</strong>'; });
$('auth-form').addEventListener('submit', async (event) => { event.preventDefault(); $('auth-error').textContent = ''; $('auth-submit').disabled = true; try { const data = await api(`/auth/${state.mode}`, { method:'POST', body:JSON.stringify({ email:$('email-input').value, password:$('password-input').value }) }); if (!data.access_token) throw new Error('Check your email to confirm your account, then sign in.'); state.token = data.access_token; localStorage.setItem('threadline_token', state.token); setUser(data.user); closeAuth(); } catch (error) { $('auth-error').textContent = error.message; } finally { $('auth-submit').disabled = false; } });

checkHealth(); restoreSession();